### ISSUE TITLE
[Bridge] EVM Fungible Token Bridge Contract

### ISSUE THREAD

**Issue by mialbu** [bane-labs/bridge-evm-contracts#1]
- [ ] [ERC20 Bridge] onNEP17Payment Method
- [ ] [ERC20 Bridge] Contract Owner
- [ ] [ERC20 Bridge] Deploy Method
- [ ] [ERC20 Bridge] Support for other ERC20 Tokens
- [ ] [ERC20 Bridge] Update Functionality (Proxy)
